Developed new method in Position class called: equalsLocationOnlyWithDistance()
amymcgovern/spacesettlers pull request #26
Opened 2022-09-16 21:20 UTC by SaiPrakash1997

equalsLocationOnlyWithDistance() method's purpose is to check if the ship reached the specified or expected location.
If the distance between the ship location and the specified location is less than 4 and greater than 0. We can say the ship successfully reached the goal location or current target.

2022-09-29 15:47 UTC, amymcgovern requested changes
Please make that one change and I'll add it!

2022-09-29 15:47 UTC, amymcgovern commented on src/spacesettlers/utilities/Position.java
> +	public boolean equalsLocationOnlyWithDistance(Toroidal2DPhysics space, Position shipPosition, Position currentPosition) {
Can you make the allowed distance a parameter?

2022-09-29 19:28 UTC, SaiPrakash1997 commented
I have made the requested changes.

2022-09-30 23:09 UTC, amymcgovern approved these changes

2022-09-30 23:09 UTC, merged